config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [ :create, :update]
  end
  resources :doses, only: [ :update, :destroy]
  get "cocktails/:id/doses/:dose_id", to: "doses#edit", as: :new_or_edit_dose
  # get "cocktails/:id/doses/:dose_id", to: "doses#edit", as: :edit_dose
  # post "cocktails/:id/doses", to: "doses#create"
end

# A user can see the list of cocktails
# A user can see the details of a given cocktail, with the dose needed for each ingredient
# A user can create a new cocktail

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  mount_uploader :photo, PhotoUploader

  validates :name, presence:true, uniqueness: true, allow_blank: false
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence:true, allow_blank: false
  validates_uniqueness_of :ingredient_id, {scope: :cocktail_id}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # before_destroy :children?
  has_many :doses
  validates :name, presence: true, uniqueness: true

  # def children?
  #   ingredient.errors.messages unless doses.any?
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(set_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  # def index
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @doses = Dose.all
  # end

  # def new
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @dose = Dose.new
  # end

  def create
    @dose = Dose.new(set_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render(:new)
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.find(params[:dose_id])
    render 'cocktails/show'
  end

  def update
    @dose = Dose.find(params[:id])
    if @dose.update(set_params)
      redirect_to cocktail_path(@dose.cocktail)
    else
      render(:edit)
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/Shared/_navbar.html.erb
<div class="container-fluid">
  <div class="navbar cocktail-navbar">
    <div class="navbar-container">
    <div class="navbar_link">
      <%= link_to "All cocktails", cocktails_path %>
    </div>
    <%= image_tag "logo", {width: 50, height: 50} %>
    <div class="navbar_link">
      <%= link_to "Create a new cocktail", "#" ,"data-toggle" => "modal", 'data-target' => '#newCoktail' %>
    </div>
  </div>
  </div>
</div>

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="newCoktail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%= render "cocktails/form" , locals: {cocktail: @cocktail = Cocktail.new}%>
      </div>
    </div>
  </div>
</div>

app/views/Shared/_new-cocktail-modal.html.erb
<div class="modal" id="form-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
<div class="form-group inputs">
  <%= f.input :name, placeholder: "Enter cocktail's name" %>
  <%= f.input :photo, label: "Choose a photo" %>
</div>
  <%= f.input :photo_cache, as: :hidden %>
<div class="cocktail-submit">
<%= f.button :submit %>
</div>
<% end %>

app/views/cocktails/index.html.erb
  <div class="overlay">
    <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
      <source src="https://res.cloudinary.com/dsvhrgnwm/video/upload/v1533924306/Three-Cocktails.webm" type="video/mp4">
    </video>
  </div>

  <div class="container">
    <% if Cocktail.count >= 4 %>
      <div class="row">
        <%= render "components/carousel" %>
      </div>
      <div class="row">
        <%= render "layouts/cards" %>
      </div>
    <% end %>
  </div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-2">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container-fluid">
  <div class="row infos">
    <div class="col-xs-8">
      <div class="cocktail-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @cocktail.photo, height: 620, width: 1400, crop: :fill %>')">
        <h1><%= @cocktail.name %></h1>
      </div>
    </div>
    <div class="col-xs-3 doses">
      <div class="row">
      <ul>
        <% @cocktail.doses.each do |dose| %>
        <li>
          <h4><%= dose.description %> - <%= dose.ingredient.name %></h4>
          <div class="dose-icons">
          <%= link_to "<i class=\"fas fa-pencil-alt\"></i>".html_safe, new_or_edit_dose_path(@cocktail.id, dose.id) %>
          <%= link_to "<i class=\"far fa-trash-alt\"></i>".html_safe, dose_path(dose.id), method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
        </li>
        <% end %>
      </ul>
      </div>
      <div class="row">
        <%= render "doses/form" %>
      </div>
    </div>
  </div>




</div>

app/views/doses/_form.html.erb
<% if @dose.new_record? %>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient, collection: Ingredient.order('name ASC') %>
    <%= f.button :submit %>
  <% end %>
<% else %>
  <%= simple_form_for @dose do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient, collection: Ingredient.order('name ASC') %>
    <%= f.button :submit %>
  <% end %>
<% end %>


<!-- = simple_form_for @news_item, :url => @news_item.new_record? ? url_for(action: 'create', controller: 'admin/news_items') : url_for(action: 'update', controller: 'admin/news_items') do |f| -->

app/views/layouts/_cards.html.erb
<div class="card-wrapper">

  <% @cocktails[3..@cocktails.length].each do |cocktail| %>
    <div class="cocktail-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill unless cocktail.photo.blank? %>')">
      <%= link_to cocktail_path(cocktail.id) do %>
        <div class="cocktail-name"> <%= cocktail.name %></div>
        <div class="cocktail-doses"> <%= cocktail.doses.count %> ingredients</div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application' %>
</head>

<body>
  <%= render "Shared/navbar" %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>